### ISSUE TITLE
npm package "codius" lists "codius-engine" as dependency, which doesn't exist

### ISSUE THREAD

**Issue by AronVanAmmers** [codius-deprecated/codius#2]
When installing codius on Ubuntu 14.04 using `sudo npm install -g codius` I get this output:

```
aron@aron-VirtualBox:~/Development/node.js$ sudo npm install -g codius
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/codius/engine) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/codius/engine) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git@github.com:codius/engine) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git@github.com:codius/engine) undefined
npm ERR! git clone git@github.com:codius/engine undefined
npm ERR! git clone git@github.com:codius/engine undefined
npm ERR! 404 404 Not Found: codius-engine
npm ERR! 404
npm ERR! 404 'codius-engine' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'codius'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-35-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "codius"
npm ERR! cwd /home/aron/Development/node.js
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/aron/Development/node.js/npm-debug.log
npm ERR! not ok code 0
```

The npm package explorer confirms this:
- `codius` lists `codius-engine` as a dependency: https://www.npmjs.org/package/codius
- But `codius-engine` doesn't exist as a package: `https://www.npmjs.org/package/codius-engine`.

As a workaround one can install `codius-engine` from github:

```
sudo npm install git+https://git@github.com/codius/codius-engine.git
```

After this, `sudo npm install -g codius` runs successfully.

**Comment by emschwartz** [comment]
Do you still have this problem?

(Sorry for the delay in responding to these issues, my github notifications
were getting lost in my personal inbox)

**Comment by bwomsm1** [comment]
Hi, 
I have kind of similar problem too but when I am running the "npm install" from Eclipse environment (MAC OS), It is showing me an error that Eclipse cannot find git in its $PATH.
When I running it from Terminal it does goes well.

npm ERR! git clone http://gitlab.cisco.com/flowcontexttools/node-flow-context.git undefined
npm ERR! git clone http://gitlab.cisco.com/flowcontexttools/node-flow-context.git undefined
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/bwarshaw/phx-app-srv/cma
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ENOGIT
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/bwarshaw/phx-app-srv/cma/npm-debug.log
npm ERR! not ok code 0

My question is how can I add git to the "npm install" run job in Eclipse Luna?

Thanks,
Boaz

**Comment by AronVanAmmers** [comment]
@emschwartz tried again on a clean Ubuntu 14.04 VM, working now. Output:

```
aron@aron-VirtualBox:~$ sudo npm install -g codius <mailto:aron@aron-VirtualBox>
npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/codius/codius-engine) <https://github.com/codius/codius-engine)>
/usr/bin/codius -> /usr/lib/node_modules/codius/bin/codius-cli.js
codius@1.0.4 /usr/lib/node_modules/codius <mailto:codius@1.0.4>
├── extend@2.0.0 <mailto:extend@2.0.0>
├── bluebird@2.4.2 <mailto:bluebird@2.4.2>
├── nopt@3.0.1 (abbrev@1.0.5) <mailto:nopt@3.0.1>
├── winston@0.8.3 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.1, colors@0.6.2, async@0.2.10, pkginfo@0.3.0) <mailto:winston@0.8.3>
├── concat-stream@1.4.7 (inherits@2.0.1, typedarray@0.0.6, readable-stream@1.1.13) <mailto:concat-stream@1.4.7>
├── tar-stream@1.1.1 (xtend@4.0.0, bl@0.9.3, readable-stream@1.0.33, end-of-stream@1.1.0) <mailto:tar-stream@1.1.1>
├── nconf@0.6.9 (ini@1.3.2, async@0.2.9, optimist@0.6.0) <mailto:nconf@0.6.9>
├── request@2.51.0 (caseless@0.8.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.0, node-uuid@1.4.2, qs@2.3.3, mime-types@1.0.2, bl@0.9.3, combined-stream@0.0.7, tough-cookie@0.12.1, http-signature@0.10.0, form-data@0.2.0, hawk@1.1.1) <mailto:request@2.51.0>
├── express@4.10.6 (merge-descriptors@0.0.2, utils-merge@1.0.0, fresh@0.2.4, cookie@0.1.2, escape-html@1.0.1, range-parser@1.0.2, cookie-signature@1.0.5, finalhandler@0.3.2, vary@1.0.0, media-typer@0.3.0, parseurl@1.3.0, methods@1.1.0, serve-static@1.7.1, content-disposition@0.5.0, path-to-regexp@0.1.3, depd@1.0.0, qs@2.3.3, on-finished@2.1.1, etag@1.5.1, debug@2.1.0, proxy-addr@1.0.4, send@0.10.1, type-is@1.5.4, accepts@1.1.4) <mailto:express@4.10.6>
├── npm@2.1.14 <mailto:npm@2.1.14>
└── codius-engine@0.1.0 (ignore@2.2.15, bigi@1.4.0, ecurve@1.0.0, lodash@2.4.1, bitcoinjs-lib@1.4.2, codius-node-sandbox@0.1.0) <mailto:codius-engine@0.1.0>
```

Before running this, I installed:
- latest node [from the PPA](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server)
- `sudo apt-get install git` (which is indeed required)

**Comment by emschwartz** [comment]
@AronVanAmmers glad to hear it worked
@bwomsm1 `git` is a dependency that must be installed separately. Take a look at this: http://git-scm.com/book/en/v2/Getting-Started-Installing-Git

**Comment by bwomsm1** [comment]
git is installed, from terminal I see "git version 1.9.3 (Apple Git-50)" (when typing "git version).

I think my problem occurs because of missing environments value for Eclipse process, but I just don't know what exactly.

**Comment by andygough1974** [comment]
I am following the instructions from https://www.npmjs.com/package/codius and i can not get Codius to install.

I have created a clean VM, with Ubuntu 14.04.01, abd have entered the follwing commands only after the install.

```
1  sudo apt-get update
2  sudo dpkg --add-architecture i386
3  sudo apt-get install libc6-i386 lib32stdc++6 libseccomp2:i386
4  sudo npm install -g codius
5  sudo apt-get install nodejs
6  sudo apt-get install npm
7  sudo npm install -g codius
```

When running the install codius I get the following messages:

andy@ubuntu:~$ sudo npm install -g codius
npm http GET https://registry.npmjs.org/codius
npm http 200 https://registry.npmjs.org/codius
npm http GET https://registry.npmjs.org/codius/-/codius-1.0.5.tgz
npm http 200 https://registry.npmjs.org/codius/-/codius-1.0.5.tgz
npm http GET https://registry.npmjs.org/concat-stream
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/codius-engine
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/nconf
npm http GET https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/tar-stream
npm http GET https://registry.npmjs.org/winston
npm http 200 https://registry.npmjs.org/codius-engine
npm http 200 https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/extend/-/extend-2.0.0.tgz
npm ERR! Error: No compatible version found: codius-engine@'codius/codius-engine#master'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "codius"
npm ERR! cwd /home/andy
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm http 200 https://registry.npmjs.org/concat-stream
npm http 200 https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/concat-stream/-/concat-stream-1.4.7.tgz
npm http GET https://registry.npmjs.org/nopt/-/nopt-3.0.1.tgz
npm http 200 https://registry.npmjs.org/nconf
npm http GET https://registry.npmjs.org/nconf/-/nconf-0.6.9.tgz
npm http 200 https://registry.npmjs.org/extend/-/extend-2.0.0.tgz
npm http 200 https://registry.npmjs.org/tar-stream
npm http GET https://registry.npmjs.org/tar-stream/-/tar-stream-1.1.2.tgz
npm http 200 https://registry.npmjs.org/concat-stream/-/concat-stream-1.4.7.tgz
npm http 200 https://registry.npmjs.org/nopt/-/nopt-3.0.1.tgz
npm http 200 https://registry.npmjs.org/nconf/-/nconf-0.6.9.tgz
npm http 200 https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/request/-/request-2.53.0.tgz
npm http 200 https://registry.npmjs.org/tar-stream/-/tar-stream-1.1.2.tgz
npm http 200 https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/bluebird/-/bluebird-2.9.6.tgz
npm http 200 https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/express/-/express-4.11.2.tgz
npm http 200 https://registry.npmjs.org/request/-/request-2.53.0.tgz
npm http 200 https://registry.npmjs.org/winston
npm http 200 https://registry.npmjs.org/bluebird/-/bluebird-2.9.6.tgz
npm http GET https://registry.npmjs.org/winston/-/winston-0.8.3.tgz
npm http 200 https://registry.npmjs.org/express/-/express-4.11.2.tgz
npm http 200 https://registry.npmjs.org/winston/-/winston-0.8.3.tgz
npm http 200 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm/-/npm-2.4.1.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-2.4.1.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/andy/npm-debug.log
npm ERR! not ok code 0

Then after some research I found someone saying I had to install the codius-engine from github, so I ran the following command:

andy@ubuntu:~$ sudo npm install git+https://git@github.com/codius/codius-engine.git
npm http GET https://registry.npmjs.org/bigi
npm http GET https://registry.npmjs.org/bitcoinjs-lib
npm http GET https://registry.npmjs.org/ecurve
npm http GET https://registry.npmjs.org/ignore
npm http GET https://registry.npmjs.org/lodash
npm http GET https://github.com/codius/codius-node-sandbox/tarball/master
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/extend
npm http 200 https://registry.npmjs.org/ecurve
npm http 200 https://registry.npmjs.org/ignore
npm http 200 https://registry.npmjs.org/bigi
npm http 304 https://registry.npmjs.org/bluebird
npm http 304 https://registry.npmjs.org/extend
npm http 200 https://registry.npmjs.org/lodash
npm http 200 https://registry.npmjs.org/bitcoinjs-lib
npm http GET https://registry.npmjs.org/ecurve/-/ecurve-1.0.1.tgz
npm http GET https://registry.npmjs.org/ignore/-/ignore-2.2.15.tgz
npm http GET https://registry.npmjs.org/bigi/-/bigi-1.4.0.tgz
npm http GET https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm http GET https://registry.npmjs.org/bitcoinjs-lib/-/bitcoinjs-lib-1.4.3.tgz
npm http 200 https://registry.npmjs.org/ignore/-/ignore-2.2.15.tgz
npm http 200 https://registry.npmjs.org/ecurve/-/ecurve-1.0.1.tgz
npm http 200 https://registry.npmjs.org/bigi/-/bigi-1.4.0.tgz
npm http 200 https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm http 200 https://registry.npmjs.org/bitcoinjs-lib/-/bitcoinjs-lib-1.4.3.tgz
npm http 200 https://github.com/codius/codius-node-sandbox/tarball/master

At which point everything stops, the install command just freezes.

Can you give me any direction please?

**Comment by wilsonianb** [comment]
Try swapping steps 1 & 2:

```
1 sudo dpkg --add-architecture i386
2 sudo apt-get update
```

It looks like libseccomp2 wouldn't actually install.

Let me know if that works, and we will update the documentation.

**Comment by andygough1974** [comment]
from a clean install again it doesnt work

```
1  sudo dpkg --add-architecture i386
2  sudo apt-get update
3  sudo apt-get install libc6-i386 lib32stdc++6 libseccomp2:i386
4  sudo apt-get install nodejs
5  sudo apt-get install npm
6  sudo npm install -g codius
```

andy@ubuntu:~$ sudo npm install -g codius
npm http GET https://registry.npmjs.org/codius
npm http 200 https://registry.npmjs.org/codius
npm http GET https://registry.npmjs.org/codius/-/codius-1.0.5.tgz
npm http 200 https://registry.npmjs.org/codius/-/codius-1.0.5.tgz
npm http GET https://registry.npmjs.org/concat-stream
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/codius-engine
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/nconf
npm http GET https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/tar-stream
npm http GET https://registry.npmjs.org/winston
npm http 200 https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/extend/-/extend-2.0.0.tgz
npm http 200 https://registry.npmjs.org/codius-engine
npm ERR! Error: No compatible version found: codius-engine@'codius/codius-engine#master'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "codius"
npm ERR! cwd /home/andy
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm http 200 https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/nopt/-/nopt-3.0.1.tgz
npm http 200 https://registry.npmjs.org/nconf
npm http GET https://registry.npmjs.org/nconf/-/nconf-0.6.9.tgz
npm http 200 https://registry.npmjs.org/extend/-/extend-2.0.0.tgz
npm http 200 https://registry.npmjs.org/bluebird
npm http 200 https://registry.npmjs.org/nopt/-/nopt-3.0.1.tgz
npm http 200 https://registry.npmjs.org/nconf/-/nconf-0.6.9.tgz
npm http GET https://registry.npmjs.org/bluebird/-/bluebird-2.9.6.tgz
npm http 200 https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/request/-/request-2.53.0.tgz
npm http 200 https://registry.npmjs.org/tar-stream
npm http GET https://registry.npmjs.org/tar-stream/-/tar-stream-1.1.2.tgz
npm http 200 https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/express/-/express-4.11.2.tgz
npm http 200 https://registry.npmjs.org/concat-stream
npm http GET https://registry.npmjs.org/concat-stream/-/concat-stream-1.4.7.tgz
npm http 200 https://registry.npmjs.org/bluebird/-/bluebird-2.9.6.tgz
npm http 200 https://registry.npmjs.org/request/-/request-2.53.0.tgz
npm http 200 https://registry.npmjs.org/tar-stream/-/tar-stream-1.1.2.tgz
npm http 200 https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/winston/-/winston-0.8.3.tgz
npm http 200 https://registry.npmjs.org/express/-/express-4.11.2.tgz
npm http 200 https://registry.npmjs.org/concat-stream/-/concat-stream-1.4.7.tgz
npm http 200 https://registry.npmjs.org/winston/-/winston-0.8.3.tgz
npm http 200 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm/-/npm-2.4.1.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-2.4.1.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/andy/npm-debug.log
npm ERR! not ok code 0

**Comment by andygough1974** [comment]
I also tried with a 32 bit linux and still not working

**Comment by wilsonianb** [comment]
The following error is resolved with `sudo apt-get install git`
Error: No compatible version found: codius-engine@'codius/codius-engine#master'

We will probably change the dependency notation in the package.json so that git is not required.

I'm now figuring out a subsequent issue:
"FATAL ERROR: Evacuation Allocation failed - process out of memory"

**Comment by andygough1974** [comment]
Ah yes, was installing from fresh VM, when i installed git and tried to install codius again, i got further this time.

I get a warning: npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/codius/codius-engine)

then it continues to install until we get to the following:

npm http 200 https://registry.npmjs.org/hoek/-/hoek-2.11.0.tgz

where it hangs

**Comment by andygough1974** [comment]
I speak too soon!
its installed after waiting for a long time at that line:

/usr/local/bin/codius -> /usr/local/lib/node_modules/codius/bin/codius-cli.js
codius@1.0.5 /usr/local/lib/node_modules/codius
├── extend@2.0.0
├── bluebird@2.9.6
├── nopt@3.0.1 (abbrev@1.0.5)
├── winston@0.8.3 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.1, colors@0.6.2, async@0.2.10, pkginfo@0.3.0)
├── concat-stream@1.4.7 (inherits@2.0.1, typedarray@0.0.6, readable-stream@1.1.13)
├── tar-stream@1.1.2 (xtend@4.0.0, bl@0.9.4, readable-stream@1.0.33, end-of-stream@1.1.0)
├── express@4.11.2 (merge-descriptors@0.0.2, utils-merge@1.0.0, methods@1.1.1, fresh@0.2.4, cookie@0.1.2, escape-html@1.0.1, range-parser@1.0.2, cookie-signature@1.0.5, finalhandler@0.3.3, vary@1.0.0, media-typer@0.3.0, parseurl@1.3.0, serve-static@1.8.1, content-disposition@0.5.0, path-to-regexp@0.1.3, depd@1.0.0, qs@2.3.3, on-finished@2.2.0, debug@2.1.1, etag@1.5.1, proxy-addr@1.0.6, send@0.11.1, type-is@1.5.6, accepts@1.2.3)
├── nconf@0.6.9 (ini@1.3.2, async@0.2.9, optimist@0.6.0)
├── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.1, node-uuid@1.4.2, qs@2.3.3, bl@0.9.4, mime-types@2.0.8, form-data@0.2.0, combined-stream@0.0.7, tough-cookie@0.12.1, http-signature@0.10.1, hawk@2.3.1)
├── npm@2.4.1
└── codius-engine@0.1.0 (ignore@2.2.15, ecurve@1.0.1, bigi@1.4.0, lodash@2.4.1, bitcoinjs-lib@1.4.3, codius-node-sandbox@0.1.0)

**Comment by wilsonianb** [comment]
Glad to hear it. The slowdown may have been a swap space thing.

Thanks for the feedback. This will help us improve the installation process.

**Comment by andygough1974** [comment]
Note, i also had to run:

sudo ln -s /usr/bin/nodejs /usr/local/bin/node

And I used 32-bit Ubuntu 14.04.01, couldnt get it to work with 64-bit

**Comment by wilsonianb** [comment]
I think installing node and npm as described on [codius.org](https://codius.org/docs/using-codius/setup-cli) is preferable to `sudo apt-get install npm`.

If you run the following, you should have npm version 1.4.28 and codius installs without hanging

```
sudo add-apt-repository ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install nodejs
```

`sudo apt-get install npm` was only giving me npm version 1.3.10

Thanks again for the feedback.
