### ISSUE TITLE
Getting error regarding git when running "npm install" task from Eclipse

### ISSUE THREAD

**Issue by bwomsm1** [codius-deprecated/codius#4]
npm WARN `git config --get remote.origin.url` returned wrong result (http://gitlab.cisco.com/flowcontexttools/node-flow-context.git) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (http://gitlab.cisco.com/flowcontexttools/node-flow-context.git) undefined
npm ERR! git clone http://gitlab.cisco.com/flowcontexttools/node-flow-context.git undefined
npm ERR! git clone http://gitlab.cisco.com/flowcontexttools/node-flow-context.git undefined
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/bwarshaw/phx-app-srv/cma
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ENOGIT
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/bwarshaw/phx-app-srv/cma/npm-debug.log
npm ERR! not ok code 0

I get this error although git is installed properly, (terminal output for "git version" command: "git version 1.9.3 (Apple Git-50)"

**Comment by emschwartz** [comment]
Unfortunately this looks like a problem with your git/eclipse setup. Is there a way to look at the PATH eclipse is using? Seems like it must not be your normal one

**Comment by bwomsm1** [comment]
With Eclipse when running any regular app/script/bash the running process has its environment values, but with "npm install" it is bit different, Eclipse does not offering the user to add environment values like in the "regular" runs.

There is such thing called "Linked Resources" but I also added there a link to: /usr/bin/git
(I followed http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Fconcepts%2Fcpathvars.htm)

Real stuck in here with that issue :-(

**Comment by bhoriuchi** [comment]
I was having a similar issue (ENOGIT error) in eclipse and was able to sort of get it working by adding a symbolic link in /usr/local/bin where npm is installed. i still get the warning "Error: Command failed: git config --get remote.origin.url" but it downloads the package from github.

ln -s /usr/bin/git /usr/local/bin/git

i am on a mac.
