### ISSUE TITLE
Dependency error libc and libstdc++ on x64 system

### ISSUE THREAD

**Issue by AronVanAmmers** [codius-deprecated/codius#5]
On a fresh Ubuntu 14.04 x64 VM I did the following:
1. Install node from PPM
2. Install git
3. Install codius using `sudo npm install -g codius`

Using `codius selftest` gives the following result:

```
$ codius selftest
info:    Running self-test. If it works, it should print "Self-test succeeded"
warn:    No secret provided! Generating a random secret, please do not do this in production.
ENOENT: The child process was unable to spawn.
Note that on x64 architectures you need to install the 32-bit versions of libc and libstdc++.
```

Also reported by someone else [in the Google group](https://groups.google.com/forum/#!topic/codius/bE-pYr-q66Y) on Windows x64.

**Comment by emschwartz** [comment]
Did you install these dependencies?

sudo apt-get install libc6-i386 lib32stdc++6

On Tue, Dec 23, 2014 at 11:51 AM, Aron van Ammers notifications@github.com
wrote:

> On a fresh Ubuntu 14.04 x64 VM I did the following:
> 1. Install node from PPM
> 2. Install git
> 3. Install codius using sudo npm install -g codius
> 
> Using codius selftest gives the following result:
> 
> $ codius selftest
> info:    Running self-test. If it works, it should print "Self-test succeeded"
> warn:    No secret provided! Generating a random secret, please do not do this in production.
> ENOENT: The child process was unable to spawn.
> Note that on x64 architectures you need to install the 32-bit versions of libc and libstdc++.
> 
> Also reported by someone else in the Google group
> https://groups.google.com/forum/#!topic/codius/bE-pYr-q66Y on Windows
> x64.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codius/codius/issues/5.

## 

Evan Schwartz | Software Engineer | Ripple Labs
[image: ripple.com] http://ripple.com

**Comment by AronVanAmmers** [comment]
Gave it a shot with: `sudo apt-get install libx32stdc++6 libc6-i386`

Results:

```
$ codius selftest
info:    Running self-test. If it works, it should print "Self-test succeeded"
warn:    No secret provided! Generating a random secret, please do not do this in production.
/usr/lib/node_modules/codius/node_modules/codius-engine/node_modules/codius-node-sandbox/deps/nacl/nacl_sdk/pepper_35/tools/sel_ldr_x86_32: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

Result of locating this file:

```
$ locate libstdc++.so.6
/usr/lib/node_modules/codius/node_modules/codius-engine/node_modules/codius-node-sandbox/deps/nacl/nacl_sdk/pepper_35/toolchain/linux_x86_glibc/x86_64-nacl/lib32/libstdc++.so.6
/usr/lib/x86_64-linux-gnu/libstdc++.so.6
/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
/usr/libx32/libstdc++.so.6
/usr/libx32/libstdc++.so.6.0.19
```

**Comment by AronVanAmmers** [comment]
Ah, note the "x". Will try again with yours.

**Comment by AronVanAmmers** [comment]
Tadaa:

```
$ codius selftest
info:    Running self-test. If it works, it should print "Self-test succeeded"
warn:    No secret provided! Generating a random secret, please do not do this in production.
DEBUG MODE ENABLED (bypass acl)
[12165,4147861824:17:57:13.148550] BYPASSING ALL ACL CHECKS
[12165,4147861824:17:57:13.154763] Native Client module will be loaded at base address 0x0000000057430000
Self-test succeeded
[12165,4147583808:17:57:13.690795] NaClRuntimeHostInterfaceReportExitStatus(0xf77eb068, 0x0)
```

Thanks.
